apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: us-east-1

#If we give managed nodegroups, AWS will handle it, otherwise we need to handle it.
managedNodeGroups:
  - name: expense
    instanceTypes: ["m5.large","c3.large","c4.large","c5.large"]
    desiredCapacity: 3
    spot: true